#ifndef ARRAY_DIMENSIONS_H
#define ARRAY_DIMENSIONS_H

#define ARRAY_DIMENSION 16
#define REPEAT(x) BOOST_PP_REPEAT(ARRAY_DIMENSION, x, 0)

#define INPUT_PRECISION 16
#define OUTPUT_PRECISION (2*INPUT_PRECISION)
// #define OUTPUT_PRECISION (1*INPUT_PRECISION)

#endif
