#!/bin/bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

read black red green yellow blue magenta cyan white < <(seq -s' ' 30 37)
colors () {
    echo -n 's/\b'$1'\b/\x1b['$2'm&\x1b[39m/I'
}

SNPS_SAIF_MAP_ON=TRUE
export SNPS_SAIF_MAP_ON
dc_shell-xg-t -x "source $dir/common_procs.tcl; source -echo $dir/synthesis.tcl" | tee dc.log | sed -e $(colors information $green) -e $(colors warning $blue) -e $(colors error $red)
